# Generated by Django 4.1.1 on 2022-10-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=300)),
                ('task', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('status_time', models.DateTimeField(auto_now_add=True)),
                ('updation_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
